In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
model = keras.models.load_model("exCifar10conv")

In [3]:
model.summary()

Model: "conv_model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
3x3_1 (Conv2D)               (None, 32, 32, 32)        896       
_________________________________________________________________
3x3_2 (Conv2D)               (None, 32, 32, 32)        9248      
_________________________________________________________________
poolconv_1 (Conv2D)          (None, 15, 15, 32)        9248      
_________________________________________________________________
dropout (Dropout)            (None, 15, 15, 32)        0         
_________________________________________________________________
3x3_3 (Conv2D)               (None, 15, 15, 64)        18496     
_________________________________________________________________
3x3_4 (Conv2D)               (None, 15, 15, 64)        36928     
_________________________________________________________________
poolconv_2 (Conv2D)          (None, 7, 7, 64)          3

In [4]:
print(type(model))
print(type(model.get_layer("3x3_3")))

<class 'tensorflow.python.keras.engine.sequential.Sequential'>
<class 'tensorflow.python.keras.layers.convolutional.Conv2D'>


In [5]:
weightsb = model.get_layer("3x3_3").get_weights()
print(len(weightsb))
for i in range(len(weightsb)):
    print(weightsb[i].shape)
    print(type(weightsb[i]))

2
(3, 3, 32, 64)
<class 'numpy.ndarray'>
(64,)
<class 'numpy.ndarray'>


In [6]:
# Layer Weights from 1 Filter
print(weightsb[0][:,:,0,0])
print(type(weightsb[0][0,0,0,0]))
print(weightsb[1][0])
print(type(weightsb[1][0]))


[[ 0.00326661 -0.02766969  0.06671857]
 [-0.01019471  0.0427774   0.01124507]
 [-0.09410954  0.0185507  -0.02385138]]
<class 'numpy.float32'>
-0.05925459
<class 'numpy.float32'>
